--use [TestDatabase2];
CREATE TABLE Final.PersonalDetails
(
	UniqueID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	FirstName NVARCHAR(32) NOT NULL,
	LastName NVARCHAR(32) NOT NULL,
	Email NVARCHAR(128) NOT NULL,
	Gender NVARCHAR(32) NOT NULL,
	StreetAddress NVARCHAR(128) NOT NULL
);